name: CWCore
main: net.clashwars.cwcore.bukkit.CWCorePlugin
version: '1.0'
author: ClashWars
description: ClashWars Core plugin
commands:
  broadcast:
    description: Broadcast a message
    usage: /<command> <msg>
    aliases: [bc,bcmsg]
  freeze:
    description: Freeze a player
    usage: /<command> [player] [on|off]
    aliases: [lock]
  god:
    description: Give a player godmode
    usage: /<command> [player] [on|off]
    aliases: [godmode]
  fly:
    description: Give a player flymode
    usage: /<command> [player] [on|off]
    aliases: [flymode]
  vanish:
    description: Vanish a player
    usage: /<command> [player] [on|off]
    aliases: [v,invis]
  gamemode:
    description: Change gamemode
    usage: /<command> <mode> [player]
    aliases: [gm]
  speed:
    description: Change walk/fly speed
    usage: /<command> <speed> [player]
  heal:
    description: Heal or set health
    usage: /<command> [player] [amt]
    aliases: [health,hp]
  nick:
    description: Change nicknames
    usage: /<command> <nick> [player]
    aliases: [nickname]
  realname:
    description: Check real name of a player
    usage: /<command> [player]
    aliases: [rname]
  time:
    description: Change the time
    usage: /<command> <get|500ticks|24:00|10pm|day|dawn|noon|afternoon|dusk|midnight|night>
    aliases: [day,night]
  removepots:
    description: Remove potion effects from a player
    usage: /<command> [player]
    aliases: [removepotions,rpots]
  invsee:
    description: See/Edit a player his inventory
    usage: /<command> <player>
    aliases: [invedit]
  item:
    description: Spawn items
    usage: /<command> <item[:data]> [amt] [optional args]
    aliases: [i]
  give:
    description: Give items to a player
    usage: /<command> <player> <item[:data]> [amt] [optional args]
  clearinv:
    description: Clear items in a player his inventory
    usage: /<command> [player] [item[:data]] [amount]
    aliases: [ci,clearinventory]
  hat:
    description: Set a player his hat
    usage: /<command> <item[:data]> [player] [optional args]
    aliases: [head]
  more:
    description: Create more items of the item in hand.
    usage: /<command> [amt]
    aliases: [stack]
  gui:
    description: Open a GUI like workbench, enchanttable, enderchest
    usage: /<command> <gui> [player]
  top:
    description: Teleport to the top.
    usage: /<command>
  suicide:
    description: Kill yourself.
    usage: /<command>
    aliases: [killme]
  kill:
    description: Kill a player.
    usage: /<command> <player>
    aliases: [slay]
  spawner:
    description: Change a mob spawner
    usage: /<command> <mob>
    aliases: [mobspawner,monsterspawner,changespawner]
  spawnmob:
    description: Spawn mobs
    usage: /<command> [mob[:data],mob[:data],...] [amount] [Optional args]
    aliases: [spawnm,mobspawn,sm,mspawn]
  powertool:
    description: Bind a command to the item you are holding.
    usage: /<command> <cmd> <args>
    aliases: [pt,macro,bind]
  teleport:
    description: Teleport yourself or a given player to <target-player>
    usage: /<command> <target-player> [player]
    aliases: [tp]
  teleporthere:
    description: Teleport a player to you
    usage: /<command> <player>
    aliases: [tphere]

  sudo:
    description: Force a player to run a command
    usage: /<command> <player> <cmd>
  whois:
    description: Show detailed info about a player
    usage: /<command> <player>
  setwarp:
    description: Set a warp with the given name
    usage: /<command> <name>
  delwarp:
    description: Delete a warp with the given name
    usage: /<command> <name>
  warp:
    description: Teleport to a warp
    usage: /<command> <name>
    aliases: [warps]
  exp:
    description: Take, Give, Set or get a player his experience
    usage: /<command> <get|add|take|set> <player> [amount[L]