name: CWCore
main: net.clashwars.cwcore.bukkit.CWCorePlugin
version: '2.0'
author: ClashWars
description: ClashWars Core plugin
commands:
  broadcast:
    description: Broadcast a message
    usage: /<command> <msg>
    aliases: [bc,bcmsg]
  fly:
    description: Toggle fly mode
    usage: /<command> [player] [on|off]
    aliases: [flymode]
  vanish:
    description: Toggle invisibility
    usage: /<command> [player] [on|off]
    aliases: [v,invis]
  gamemode:
    description: Change gamemode
    usage: /<command> <mode> [player]
    aliases: [gm]
  speed:
    description: Change walk/fly speed
    usage: /<command> <speed> [player]
  heal:
    description: Heal or set health
    usage: /<command> [player] [amt]
    aliases: [health,hp]
  tag:
    description: Change nametag above head
    usage: /<command> <tag> [player]
    aliases: [nametag]
  time:
    description: Change the time
    usage: /<command> <get|500ticks|24:00|10pm|time_name>
    aliases: [day,night]
  removepots:
    description: Remove potion effects
    usage: /<command> [player] [potionEffectType]
    aliases: [removepotions,rpots,removepot,rpot]
  invsee:
    description: See/Modify a player his inventory
    usage: /<command> <player>
    aliases: [invedit]
  item:
    description: Spawn items
    usage: /<command> <item[:data]> [amt]
    aliases: [i]
  give:
    description: Give items to a player
    usage: /<command> <player> <item[:data]> [amt]
  clearinv:
    description: Clear items in a player his inventory
    usage: /<command> [player] [item[:data]] [amount]
    aliases: [ci,clearinventory]
  gui:
    description: Open a GUI like workbench
    usage: /<command> <gui> [player]
  top:
    description: Teleport to the top.
    usage: /<command>
    aliases: [topp,roof]
  setspawn:
    description: Set the server spawn
    usage: /<command>
  spawn:
    description: Teleport to the spawn.
    usage: /<command>
  spawner:
    description: Change a mob spawner
    usage: /<command> <mob>
    aliases: [mobspawner,monsterspawner,changespawner]
  spawnmob:
    description: Advanced mob/entity spawning
    usage: /<command> mob[,mob,mob] [amt]
    aliases: [spawnm,mobspawn,sm,mspawn]
  powertool:
    description: Bind a command to a tool
    usage: /<command> <cmd + args>
    aliases: [pt,macro,bind]
  teleport:
    description: Teleport to a player
    usage: /<command> <target-player> [player]
    aliases: [tp]
  teleportpos:
    description: Teleport to a location or world
    usage: /<command> <x,y,z[:world]> [player]
    aliases: [tppos, tploc]
  sudo:
    description: Force a player to run a command
    usage: /<command> <player> <cmd + args>
  setwarp:
    description: Set a warp
    usage: /<command> <name>
  delwarp:
    description: Delete a warp
    usage: /<command> <name>
  warp:
    description: Teleport to a warp location
    usage: /<command> <name>
  warps:
    description: List all warps
    usage: /<command>
  exp:
    description: modify a player his experience
    usage: /<command> <get|add|take|set> <player> [amount[L]]
  firework:
    description: Give or launch fireworks.
    usage: /<command> <amt> [player]
    aliases: [fw]
  particle:
    description: Play particle effects.
    usage: /<command> <particle> [params]
    aliases: [particles]
  iteminfo:
    description: Show information about held item
    usage: /<command>
    aliases: [ii, itemi]
  effect:
    description: Apply a potion effect
    usage: /<command> <effect> [duration] [strength]
    aliases: [potioneffect, potion]
  sound:
    description: Play a sound
    usage: /<command> <sound> [volume] [pitch]
    aliases: [playsound]