name: CWCore
main: net.clashwars.cwcore.bukkit.CWCorePlugin
version: '1.0'
author: ClashWars
description: ClashWars Core plugin
commands:
  book:
    description: Book commands
    usage: /<command> help
  chest:
    description: Chest commands
    usage: /<command> help
  firework:
    description: Customize your rocket
    usage: /<command>
  tploc:
    description: Teleport a player to a location
    usage: /<command> player x,y,z world
  exp:
    description: Give/Take/Show experience
    usage: /<command> <player> <exp[L]>
  bc:
    description: Broadcast a message
    usage: /<command> <msg>
    aliases: [broadcast,bcmsg]
  freeze:
    description: Freeze a player
    usage: /<command> [player] [on|off]
  gm:
    description: Change gamemode
    usage: /<command> <mode> [player]
  heal:
    description: Heal or set health
    usage: /<command> [player] [amt]
    aliases: [health,hp]
  nick:
    description: Change nicknames
    usage: /<command> <nick> [player]
  realname:
    description: Check real name of a player
    usage: /<command> [player]
  time:
    description: Change the time
    usage: /<command> <get|500ticks|24:00|10pm|day|dawn|noon|afternoon|dusk|midnight|night>
  removepots:
    description: Remove potion effects from a player
    usage: /<command> [player]