name: CWCore
main: com.pqqqqq.cwcore.bukkit.CWCorePlugin
version: '1.0'
author: Pqqqqq
description: ClashWars Core plugin
commands:
  book:
    description: Book commands
    usage: /<command> help
  chest:
    description: Chest commands
    usage: /<command> help
  firework:
    description: Customize your rocket
    usage: /<command>
  tploc:
    description: Teleport a player to a location
    usage: /tploc player x,y,z world
  givexp:
    description: Gives a player experience
    usage: /<command> <amount> <player>